### ISSUE TITLE
为什么pull下来后，无法上网？

### ISSUE THREAD

**Issue by bluebird88** [wilon/lantern#1]
---- curl -vv https://www.google.com/humans.txt 
。。。。。。
< HTTP/1.1 200 OK
< Date: Tuesday, 05-Jun-18 10:19:35 UTC
< Keep-Alive: timeout=38
< Content-Length: 0
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Closing connection 0
curl: (35) Encountered end of file

-----后台错误信息：
 Jun 05 10:19:55.475 - 10m56s ERROR balancer: balancer.go:372 Unable to dial via fp-vltok1-20180530-556-lampshade (45.77.129.2:15170) to connect://www.google.com:443: context deadline exceeded on pass 0...continuing [beam=23 detour=false error=Unable to dial via %v to %s://%s: %v on pass %v%v error_location=github.com/getlantern/flashlight/balancer.(*balancedDial).onFailure (balancer.go:372) error_op= error_text=Unable to dial via fp-vltok1-20180530-556-lampshade (45.77.129.2:15170) to connect://www.google.com:443: context deadline exceeded on pass 0...continuing error_type=errors.Error local_proxy_type=http op=balancer_dial origin=www.google.com:443 origin_host=www.google.com origin_port=443 root_op=proxy user_agent=curl/7.29.0]
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/balancer.(*balancedDial).onFailure (balancer.go:372)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/balancer.(*balancedDial).dial (balancer.go:295)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/balancer.(*Balancer).DialContext (balancer.go:228)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/client.(*Client).getDialer.func1 (client.go:461)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/client.(*Client).getDialer.func4 (client.go:518)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/client.(*Client).doDial (client.go:443)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/client.(*Client).dial (client.go:415)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/client.(*Client).(github.com/getlantern/flashlight/client.dial)-fm (client.go:195)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).proceedWithConnect (proxy_connect.go:121)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).processRequests (proxy_http.go:187)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).handle (proxy_http.go:142)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).Handle (proxy_http.go:45)
 ERROR balancer: balancer.go:372   at github.com/getlantern/flashlight/client.(*Client).handle (handler.go:39)
 ERROR balancer: balancer.go:372   at runtime.goexit (asm_amd64.s:2337)
 ERROR balancer: balancer.go:372 Caused by: context deadline exceeded

我看其实是报告 连接到google。com超时，我装了本地的lantern，也是同样的情况。
这是什么问题？

**Comment by wilon** [comment]
你打开 Lantern，`设置` -> `HTTP(S)代理服务器：` 后面的 ip 端口复制，如 Mac：127.0.0.1:50958

测试命令：`curl -kvx 127.0.0.1:50958 http://www.google.com/humans.txt`

能看到 Google is built by... 就是 Lantern 启动成功，你的代理设置有问题。
