### ISSUE TITLE
如何升级为专业版

### ISSUE THREAD

**Issue by terenceztc** [wilon/lantern#10]
请问如何升级为专业版？

**Comment by wilon** [comment]
第一种方法，浏览器打开：`http://{docker IP}:8080/wilonlantern/`，然后界面操作就行了。

第二种方法比较麻烦，就是找到已登录专业版账户的机器，打开配置文件，复制下面两行（专业版账户配置）：
```
userID: xxxxxx
userToken: xxxxxx
```
复制到`docker lantern container`容器内部`~/settings.yaml`里，若存在就替换掉，重启即可。
