### ISSUE TITLE
这个ubuntu中安装的蓝灯 不能认证成专业版吧？

### ISSUE THREAD

**Issue by ZhangHouhou** [wilon/lantern#11]
只有500M 用完了就会降速吗

**Comment by wilon** [comment]
可以认证 #10

**Comment by ZhangHouhou** [comment]
> 可以认证 #10

请问怎么认证？我买了专业版

需要用图形界面连接 到docker中的ubuntu然后启动蓝灯的本地页面查看认证码？

**Comment by ZhangHouhou** [comment]
蓝灯那个本地服务器地址是多少呀？
http://0.0.0.0:8080/wilonlantern run 起来这个地址 访问不到

**Comment by wilon** [comment]
win7: http://192.168.99.100:8080/wilonlantern/
win10: http://127.0.0.1:8080/wilonlantern/
