### ISSUE TITLE
端口不能访问

### ISSUE THREAD

**Issue by kerrer** [wilon/lantern#3]
8080  3128 都不能访问，没有任何返回
This page isn’t working 127.0.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by Victor2333** [comment]
You need to use localHTTPToken in lantern.It is in the container /root/.lantern/settings.yaml

**Comment by Victor2333** [comment]
And visit http(s)://domain:port/${localHTTPTOKEN}/ to login

**Comment by Victor2333** [comment]
8080 port if for ui.
