### ISSUE TITLE
Lentern无法使用

### ISSUE THREAD

**Issue by Codeusername** [wilon/lantern#4]
请提供可靠地联系方式解决用户问题。
目前使用专业版账户（18个月剩余时长），无法正常连接服务器（显示连接，但是打不开YouTube、google等网站；尝试访问YouTube、google等网站时，会变成“连接中”状态，并且无法成功连接并访问网站。）
已经通过排查自行处理一部分操作（卸载Lantern并且重新安装；清除用户文件夹下数据并且重新安装；还原Host文件并且重新安装；抹掉硬盘并且重新安装windows 10 Pro 1809并且重新安装Lantern，以上均无法修复。）
邮件提交状态以后石沉大海，没有任何管理员或者是技术支持进行任何形式的回复（已经将近两周了。）
自春节期间（2019.2.5）至今Windows、macOS Mojave均出现以上问题。
请管理员或者是技术支持帮我查看一下我的账户授权以及账户状态（账户：[664166671@qq.com](mailto:664166671@qq.com)）。
谢谢。

**Comment by wilon** [comment]
此项目为个人项目，非官方支持，请移步：https://github.com/getlantern/lantern-binaries/issues
