### ISSUE TITLE
Support alpine

### ISSUE THREAD

**Issue by Victor2333** [wilon/lantern#5]
I wonder if this docker image could support alpine linux is better than ubuntu 14.04.

**Comment by wilon** [comment]
The Lantern installers binary only support a Debian-based environment.

References:
https://github.com/getlantern/lantern-binaries
https://unix.stackexchange.com/questions/449939/building-deb-on-alpine

**Comment by Victor2333** [comment]
what about try to build from source 
[https://github.com/getlantern/lantern/tree/5.3.8#building-lantern-for-running-on-a-server](github link)

**Comment by Victor2333** [comment]
what about try to build from source ?
[github link](https://github.com/getlantern/lantern/tree/5.3.8#building-lantern-for-running-on-a-server)

**Comment by Victor2333** [comment]
I have tried and it worked.
p.s. when trying to build from source code. You need to edit Dockerfile and add 
`RUN yum install -y yum-plugin-ovl`
to avoid rpm database error.

**Comment by wilon** [comment]
Good job, and welcome give me a pr.

**Comment by Victor2333** [comment]
It failed because of alpine linux doesn't have standard c++ library.But build from source can make lantern work on centos and other linux.Trying to set build without C following [issue](https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host).If it worked i will let you know @wilon
