### ISSUE TITLE
请问是否可以用自己ID登录使用

### ISSUE THREAD

**Issue by JasonDevStudio** [wilon/lantern#6]
请问是否可以用自己ID登录使用

**Comment by wilon** [comment]
https://github.com/wilon/lantern/commit/7976dd0d87b47b25e37a7bad37cc8e4b1a71a77c 修复了界面的bug

请重新执行：
```
docker pull wilon/lantern
docker run -itd --restart=always --name lantern -p 3128:3128 -p 8080:8080 wilon/lantern
```

然后浏览器打开：http://0.0.0.0:8080/wilonlantern
